modLoader = "javafml" #mandatory
loaderVersion = "[28,)" #mandatory
license='''
Copyright 2020 Duncan Brasher (Dunkmania101)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
'''
issueTrackerURL="https://github.com/Dunkmania101/SpatialHarvesters/issues" #optional
[[mods]] #mandatory
modId = "spatialharvesters" #mandatory
version = "0.9.6" #mandatory
displayName = "Spatial Harvesters" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/spatial-harvesters" #optional
logoFile="spatialharvesters-logo.png" #optional
authors = "Dunkmania101" #optional
description = '''
Adds harvesters that gather resources from space-time itself!
Inspired by EnvironmentalTech.
'''
#[[dependencies.spatialharvesters]] #optional
#    modId="forge" #mandatory
#    mandatory=true #mandatory
#    versionRange="[28,)" #mandatory
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.spatialharvesters]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.15.2]"
#    ordering="NONE"
#    side="BOTH"
